theme: jekyll-theme-hacker
title: [Projetos - 2022.1]
description: [Projetos orientados pelo Prof. Thiago G. Traue e outros]
show_downloads: false
logo: /assets/logo.png
github:
  is_project_page: false